# Generated by Django 4.2.6 on 2024-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='linkdin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pdf_file_ikteva',
            field=models.FileField(blank=True, null=True, upload_to='pdf_file_ikteva/'),
        ),
        migrations.AddField(
            model_name='company',
            name='pdf_file_local',
            field=models.FileField(blank=True, null=True, upload_to='pdf_file_local/'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
